### ISSUE TITLE
white screen when starting appimage on linux

### ISSUE THREAD

**Issue by blankuser48** [lexoyo/stastic-designer#13]
when i start the appimage after giving it execute permission the program just shows a white screen

![image](https://github.com/lexoyo/stastic-designer/assets/112839462/f8ab2091-da51-456c-8701-539e03a0420b)

**Comment by lexoyo** [comment]
Hello
I'm sorry this tool has been replaced by silex v3
https://v3.silex.me

I invite you to read our kickoff article here: https://www.silexlabs.org/silex-v3-kickoff/

Links

https://short.silex.me/docs
https://short.silex.me/video_en
https://short.silex.me/community 
https://short.silex.me/news_en
